### PR TITLE
CLI extensibility

### LINKED ISSUE #161: A way to integrate new textX CLI subcommands
Related to #148 #42 

See the initial discussion [here](https://github.com/textX/textX/issues/148#issuecomment-456643632).

The idea would be to provide an extension point for new sub-commands. In that way `textx` cli could be extended by new sub-commands by both official and un-official projects installable using `pip`.

See how it is done in the [textx-tools](https://github.com/textX/textx-tools/blob/master/setup.py#L59) project with `list-gens` and `list-langs` commands. For example [this](https://github.com/textX/textx-tools/blob/master/txtools/gen.py#L12).

### PR DESCRIPTION
**Pull request by igordejanovic**
closes #161 

This PR:
- migrates CLI to the [click](https://github.com/pallets/click) library,
- implements CLI extensibility. Other Python project may now add `textx` sub-commands and sub-command groups. Those are dynamically discovered. It is enough for the project to register extension point and be installed via `pip`. ~~This PR will be open until the docs are written~~. For now please see the test.

@goto40 @danixeee Please test/review.

### CODE REVIEW

**Comment by igordejanovic** [comment]
Related to #148 
@Aluriak Please test if this feature will be what is needed to integrate doc generator with the textX cli.

**Comment by goto40** [comment]
Do I understand correctly, that the purpose is to allow meta modeling tools to register? Like a generic model pretty printer, a meta model docu generator, etc.?

**Comment by igordejanovic** [comment]
Yes, instead of each tool having its own CLI command and forcing user to remember a bunch of CLI commands this enable tools to register their CLI commands under `textx` command so the user just use `textx` to query and invoke commands.

You can test this by installing textX from this branch source with `pip install -e`, than install the example project from the test `subcommands/example_project`. When you call `textx` you will see now that there is one new subcommand and one subcommand group registered which you can invoke just like you would invoke built-in commands (`check` and `visualize`).

**Comment by danixeee** [comment]
Looks good to me. I have successfully added `textxls` command group to the textX CLI and it is working fine. Here are `textx-ls-core` [entry points](https://github.com/textX/textX-LS/blob/danixeee/textxfile-lang-support/textX-LS/core/setup.py#L39).

Model validation for `Textxfile` with `textxls` CLI:
image

**Comment by goto40** [comment]
I will try to add a Plantuml export, but I need some time (5-10 days). You can proceed and close if you need to - and we can reopen in cases of problems...

**Comment by igordejanovic** [comment]
Great!

@danixeee I would suggest group name to be just `ls`. No need for a `textx` prefix.

@goto40 Sure, take your time. Is your idea to make separately installable tool to provide this option or to make it a part of the `textx` iteself? Maybe we could have it as an option on `visualize` command (e.g. `dot` being the default and `plantuml` being optional?
Ok, I'm merging this PR and if there is any issue we'll reopen.

**Comment by igordejanovic** [comment]
I have merged this PR and closed #161 in order to have it more accessible for ongoing tools development. The docs will be tracked on #163.

**Comment by igordejanovic** [comment]
Added the [docs on CLI extensibility](http://textx.github.io/textX/latest/textx_command/#extending-textx-command).

**Comment by Aluriak** [comment]
Sorry for late reply, i had a lot on my plate lastly. I am currently working on this. Works well, but some issues are incoming.

**Pull request merged**
