### PR TITLE
Fix infinite recursion

### PR DESCRIPTION
**Pull request by markusschmaus**
## Code review checklist

- [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [x] Title summarizes what is changing
- [x] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/

(Inception PR)

This fixes the infinite recursion we are getting when trying to call super suing type(obj). By defining the replacement methods inside a method each replacement is bound to the original class without needing to look it up.

### CODE REVIEW

**Review by goto40 — COMMENTED** [review]
Awesome! Can you add a small unittest?

**Comment by markusschmaus** [comment]
Most of this PR addresses a problem with python2 which led all tests on my end fail. I added a small test which tests the correct behavior in the case of attrs classes which inherit from each other, which is also fixed in this PR.

**Comment by markusschmaus** [comment]
I fixed this error:
```
E               ValueError: 

Non keyword-only attributes are not allowed after a keyword-only attribute
```
Newer versions of attrs (including the one I use) no longer have this restriction. https://github.com/python-attrs/attrs/pull/559

**Comment by igordejanovic** [comment]
Thanks @markusschmaus, great work! This looks good to me.

With this change we can publish this in the next minor release and drop Python 2 in the next major release.

I noticed a [leftover docstring](https://github.com/textX/textX/blob/bf5dd7bd491d631285483280b7fd0e0be24aef97/tests/functional/test_user_class_attrs_frozen.py#L22) so you can remove it. BTW, do you want to clean this branch yourself or should I squash merge?

**Comment by markusschmaus** [comment]
Squash merge sounds great to me

**Pull request merged**
