### PR TITLE
textx version command

### PR DESCRIPTION
**Pull request by igordejanovic**
Command to print version info from the CLI.

## Code review checklist

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by goto40 — APPROVED** [review]
Good job! 

Would it be useful to provide a common version api for languages /generators?

Or to provide a show-all-registered-textX-components-versions command?

**Comment by igordejanovic** [comment]
@goto40 Good idea. That would be a very useful info. I guess that we could add version info in the output of `list-languages/generators`.

**Comment by goto40** [comment]
Maybe create a ticket, if you are not sure how to implement it...

**Comment by igordejanovic** [comment]
Agree. Created #220

**Pull request merged**
