### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by igordejanovic**
This PR solves #307 migration to GitHub Actions.

Overall, the process of migration was surprisingly smooth.

This PR also drops official support for deprecated Python versions as the maintenance of CI support as the Python ecosystem is moving forward would be too time consuming.

## Code review checklist

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by goto40** [comment]
Very good!

I have a minor comment concerning dropping python 2.x support: 
 - [ ] do we still need `six.py`?

I checked via grep for python 2.x:
```
egrep -in 'python.*2' $(find . -name "*.py")
./textx/model.py:470:                                    # Python 2: func is converted to
./textx/six.py:1:"""Utilities for writing code that runs on Python 2 and 3"""
./textx/six.py:170:    with Python 2.5 and all existing versions of Python3
./textx/six.py:724:        """The new-style print function for Python 2.4 and 2.5."""
./textx/six.py:828:def python_2_unicode_compatible(klass):
./textx/six.py:830:    A decorator that defines __unicode__ and __str__ methods under Python 2.
./textx/six.py:833:    To support Python 2 and 3 with a single code base, define a __str__ method
./textx/six.py:838:            raise ValueError("@python_2_unicode_compatible cannot be applied "
./textx/lang.py:371:        # Python 2.x
```
 - [ ] I also see `lang.py` --> seems to be ok - could be cleaned up if someone changes something there (maybe add a note/comment to encourage use of `nonlocal` for `has_change`?)
 - [ ] and `model.py` --> I have no idea if/how this should/could be changed.

**Comment by igordejanovic** [comment]
@goto40 Good points. Yes, we can gradually remove Python 2.x code. This PR just drops official support (i.e. CI testing) but we don't have to remove the code immediately. I suggest to leave `six` for some time and gradually remove it (and other Python 2.x workarounds) as the time permits.

**Review by goto40 — APPROVED** [review]
LGTM. Good work!

**Comment by igordejanovic** [comment]
@goto40 Thanks!

**Pull request merged**
