### PR TITLE
Issue155 test code

### PR DESCRIPTION
**Pull request by goto40**
The example code of #155. 
I think it is a very good example (Thank you @Aluriak).

### CODE REVIEW

**Comment by goto40** [comment]
Hmm... I think I max have reproduced the effect observed by @Aluriak for python 3.5. See Travis!

**Comment by goto40** [comment]
It is unclear to me why it is not failing on my fork? (see next comment)

**Comment by goto40** [comment]
After restarting the build for this pr on Travis manually, the test passed... Then again failed. Needs to be analyzed!

**Comment by igordejanovic** [comment]
Hm, definitely, that non-determinism is disturbing. Might be an issue of using dicts and relying on items order?

**Comment by Aluriak** [comment]
> Hm, definitely, that non-determinism is disturbing. Might be an issue of using dicts and relying on items order?

Could be, although dict order was introduced in 3.6 IIRC, and all samples were tested with 3.6+ on my side.

Also, if the theoretical framework should be determinist, then use of unordered dict shouldn't change anything. My point is, even if dict were unordered, you shouldn't have any non-deterministic behavior, unless you explicitely rely on dict order to encode some determinism-related behavior.

To test that, one funny way is to run all the tests, but with an added artificial mixing of dictionnaries (mix keys, rebuild a dict using that new key order). If a dict order is found important, then i see two solutions:

- indicate explicitely that the order in this dictionnary is necessary, and use instead `collections.OrderedDict` to ensure 3.5- compatibility
- store the order/determinism-related-behavior by other means

**Comment by igordejanovic** [comment]
@Aluriak Sure. The underlying theoretical framework (PEG) is deterministic but implementation still doesn't have to be, which should be treated as a bug. Having test fails sometimes, and only on 3.5 is very curious. @goto40 definitely should be analyzed and the root case should be identified.

**Comment by goto40** [comment]
Internal note: 
 * High level effect: The difference seems to happen with "process_node" in model.py (a lot of printf-debugging).
 * The difference emerges from ```METAMODEL["ParenExpr"]._tx_type``` being "abstract" one time and "match" another time.
 * \_\_iter\_\_ in metamodel.py depends on the dict order. Some experiments with sorted keys (locally in \_\_iter\_\_) did not yield the error, even when inverting the order (result not 100% sure, since only a few experiments were made)
 * in lang.py: "def _has_nonmatch_ref(rule):" can return None (actually happens; seems "normal"; should maybe be False in that case)
 * In "lang.py": "def _determine_rule_types(self, metamodel):" iterates over the metamodel entries. 

**Summary:**

This was an observation session (no commit/push). I just played with python 3.5 and a lot of printfs... I could reproduce the effect quite often (>1 effect per 10 runs).

The key problems seems to be ```METAMODEL["ParenExpr"]._tx_type``` being different in some cases, which  somehow causes the effect. Maybe ```_determine_rule_types(self, metamodel)``` in lang.py is a good starting point for a walkthrough.

**Comment by igordejanovic** [comment]
@goto40 Thanks for the insights. Will give it a debugging try on 3.5 as soon as I find some time. It really bugs me why does it happen on this version only.

**Comment by goto40** [comment]
As @Aluriak mentioned : they changed the dicts in 3.6. This is also what I
found on SO.

**Comment by goto40** [comment]
A candidate for a quickfix could be, as noted above,  ```__iter__``` in metamodel.py
>>    * ```__iter__``` in metamodel.py depends on the dict order. **Some experiments with sorted keys (locally in __iter__) did not yield the error**, even when inverting the order (result not 100% sure, since only a few experiments were made)

 * But I prefer to have the root cause completely understood (instead of "just sorting the one or the other dict").
 * However, a quick-fix could help us to jump to 2.x.x. We could still create a new ticket or leave the relevant tickets open.

**Pull request merged**
