### PR TITLE
Fix lost encoding for multi meta-model. Close #81

### LINKED ISSUE #81: Encoding is lost when using Multi meta-model
I have model (meta-model A) which imports models of another meta-model B. Model-Files of model B do not work with `utf-8` and used encoding is lost.

I assumed the encoding would be propagated.

```
Traceback (most recent call last):
  File "...\Generator.py", line 36, in getModel
    mmA.model_from_file(filePath, encoding='iso-8859-1')
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 505, in model_from_file
    return self.internal_model_from_file(file_name, encoding, debug)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 542, in internal_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 260, in get_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 285, in get_model_from_str
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 614, in parse_tree_to_objgraph
    scope_provider.load_models(model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\providers.py", line 297, in load_models
    self._load_referenced_models(model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\providers.py", line 282, in _load_referenced_models
    filename_pattern, model=model, glob_args=self.glob_args)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\__init__.py", line 159, in load_models_using_filepattern
    self.load_model(the_metamodel, filename, is_main_model))
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\__init__.py", line 213, in load_model
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 542, in internal_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 255, in get_model_from_file
    model_str = f.read()
  File "...\Python\Python37\lib\codecs.py", line 708, in read
    return self.reader.read(size)
  File "...\Python\Python37\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 4121: invalid start byte
```

### PR DESCRIPTION
**Pull request by fgro93**
see #81

### CODE REVIEW

**Review by goto40 — COMMENTED** [review]
Thank you very much for your work. I can have a look at your pull request next week.

**Comment by goto40** [comment]
Thank you very much for your analysis.

I did not make any tests with the encoding. I greatly appreciate this additional tests to uncover errors in the textx scope provider/multi model code.

However, the unittests fail (see the travis link above: "All checks have failed" -> "Details"). If you have time, you may have a look at it. Else I will analyze it the next days.

You can also run the tests locally (see travis.yml how to start the tests).

**Comment by fgro93** [comment]
I will have a look at the failing tests tonight.

**Comment by igordejanovic** [comment]
@fgro93 Thanks for the contribution! I've just put up [a detailed contribution guide](https://github.com/igordejanovic/textX/blob/78fe21cc4a4563d8e70a2fd12089690307fe84a1/docs/about/contributing.md) which should hopefully enable new contributor to start easier. It is not merged yet to master.  You can take a look how to setup your environment properly for tests. For now install `flake8` with pip and run only on your tests.

**Comment by goto40** [comment]
I fixed the problem. Thank you again for the work. More comments are welcome!
I also added a test.

**Comment by goto40** [comment]
I will close this PR. All changes are included in PR #85 .

**Pull request closed without merging**
