### PR TITLE
Better dot visualization

### PR DESCRIPTION
**Pull request by igordejanovic**
Improved dot visualization of meta-models:

- rendering of base-types removed
- optional/required attrs rendering changed
- all match rules are rendered as a single table

If this looks better I'll update images in the docs.

## Code review checklist

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by goto40** [comment]
Very nice!

I checked `examples_StateMachine_state_machine.dot.png` after running `python render_all_grammars.py`. Much easier to read.

Do you also plan to update the plantuml version (e.g. `examples_StateMachine_state_machine.png`)?

**Comment by igordejanovic** [comment]
> Do you also plan to update the plantuml version (e.g. `examples_StateMachine_state_machine.png`)?

After looking at `pu` outputs I think we should reorder type/name. E.g. instead of `ID name` we should render `name: ID` which will be better aligned with both dot and standard UML class diagramming notation. What do you think?

I don't know if PlantUML has some similar feature that would enable rendering of match rules as a table.

**Comment by goto40** [comment]
I played with the *.pu file manually: I added 
```
title
  Matched rules:
  |= Name  |= Rule details |
  | Comment | \\/\\*(.\|\\n)*?\\*\\/ |
  | Keyword | end\|events\|resetEvents\|state\|actions |
  | SMID | ID |
end title
```
to add a table as title (maybe we could also add it as a note). I added a backslash before all backslashes and pipe symbols.

The result is attached.
examples_StateMachine_state_machine

**Comment by goto40** [comment]
> render `name: ID` which will be better aligned with both dot and standard UML class diagramming notation. What do you think?

Yes.

**Comment by igordejanovic** [comment]
@goto40 Looks really good. Yes, maybe a note would be better. `Matched rules:` should be `Match rules`. Could you add your changes to this branch? Also, when your are on it please reorder the name/type.

**Comment by goto40** [comment]
I am happy to do it

**Comment by goto40** [comment]
I added a first version.
- I adapted the plantuml renderer in the same way as the dot renderer
- I reused the `dot_match_str` function for plantuml support
- I flipped name/type

To be reviewed carefully:
- I adapted the `dot_match_str` to handle, e.g. "Not" in `state_machine.tx`. **Maybe I am too generic here**... (else w/o type check; see diff to previous version).
- I had to pass the "known" match rules, in order to not expand them in the `dot_match_str` function. See image below, compared to the image above (usage of `Keyword` in the `SMID` rule). This fix was also applied for the dot export.

Any idea how we could design some good unittests here? Of course we could just make some regexp checks... Would be better than nothing. 

I have the feeling that the export function is not tested enough.

examples_StateMachine_state_machine
examples_StateMachine_state_machine dot

The grammar:
```
...
Keyword:
    'end' | 'events' | 'resetEvents' | 'state' | 'actions'
;
...
SMID:
    !Keyword ID
;
...
```

**Comment by igordejanovic** [comment]
@goto40 Great work

> * I adapted the `dot_match_str` to handle, e.g. "Not" in `state_machine.tx`. **Maybe I am too generic here**... (else w/o type check; see diff to previous version).

Looks good. I think this approach is perfectly fine.

> Any idea how we could design some good unittests here? Of course we could just make some regexp checks... Would be better than nothing.
> 
> I have the feeling that the export function is not tested enough.

You are right, we are not covering this as we should. I don't have an idea what would be a good approach. I don't want to put something that will require frequent test updates. We can think about it and in the meantime we can do visual inspection over produced images.

I did some more testing and found two more problems. Fixed in the previous two commits. By running `render_all_grammars.py` over the whole code and visual inspection it looks very good to me.

**Review by goto40 — APPROVED** [review]
Very good!

Ok for me...

**Pull request merged**
