### PR TITLE
enforce exact name matches in RelativeName and ExtRelativeName

### LINKED ISSUE #267: [Ext]RelativeName scope providers accept any referenced object that contains the lookup name in its name
Example:

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/tests/functional/test_scoping/components_model1/example.components#L27 
 `output1`  can be changed to any substring (e.g., `o`, `out`, `pu`) and the tests still pass.

If multiple objects match the substring, the first (in parsing order or along the extension chain) will be returned.

This seems to be a regression of #186:

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L593
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L602

and

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L661
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L671

@goto40's docstring mentions this new behavior, but I doubt that these matches were intended:
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L573

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Fixes #267, as suggested in https://github.com/textX/textX/issues/267#issuecomment-669430386

## Code review checklist

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
@goto40: I think I misunderstood your comment at first. The latter version post-processes the result.

**Review by goto40 — APPROVED** [review]
Well done, @ipa-mdl! Thank you very much for your contribution.

@igordejanovic, if you have no further comments, this could be merged.

**Comment by mathias-luedtke** [comment]
I just rebased to take out the first version and its revert commit.

**Comment by igordejanovic** [comment]
LGTM. Great work @ipa-mdl. Thanks for the contribution.
Merging.

**Pull request merged**
