### PR TITLE
Click fixes

### PR DESCRIPTION
**Pull request by igordejanovic**
This PR:
- fixes the version spec for Click (relaxes it to use any version between 7.0 and 8.0)
- removes wrapping of bare `Exception` with `ClickException` as we shouldn't expect anything than textX exceptions in the normal flow of work. If any other exception is raised we should throw it unchanged.

## Code review checklist

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] Changelog(s) has/have been updated, as needed (see `CHANGELOG.md`, no need
      to update for typo fixes and such).

[commit messages]: https://chris.beams.io/posts/git-commit/7.0

### CODE REVIEW

**Comment by goto40** [comment]
Looks good... I added the ClickException mainly because I had an issue with the exit code (not indicating an error when some problem occurred).

This seems to work now. However, I get a strange effect (although the unittests run successfully):

After running the unittests I get an error (`AttributeError: _tx_reference_resolver`) when doing this:
```
textx check tests/functional/registration/projects/flow_dsl/tests/models/data_flow.eflow
```
do you get the same? I do not understand what I messed up...

**Comment by igordejanovic** [comment]
@goto40 I get the same error. It seems that `check` is broken for registered languages. Checked for released 2.1.0 and got the same error. Investigating.

**Comment by igordejanovic** [comment]
@goto40 I figured it out. Root model was registered two times in `all_models.filename_to_model`, once with relative name and the other time with full path. I did a fix but erroneously pushed it to master. Please see the last commit on the master. If you agree with the fix we'll leave it there.

**Comment by goto40** [comment]
Very good!

**Review by goto40 — APPROVED** [review]

**Pull request merged**
