### PR TITLE
Make it explicit that `tx` files are for Grammar

### PR DESCRIPTION
**Pull request by simkimsia**
Because I asked a stupid question in SO here https://stackoverflow.com/questions/53878282/is-it-possible-to-add-comments-to-tx-files-for-textx-if-so-how/53878352#53878352

### CODE REVIEW

**Comment by igordejanovic** [comment]
Thanks. Yeah, this seems to be a common pitfall :)

Could you please squash these 3 commits into one, remove `!` before the first link (to the grammar) and reformat that line to max 80 column width?

You can use [git interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to change history (do squash). You will have to do force push to change this branch.

**Comment by simkimsia** [comment]
@igordejanovic copy that. I seldom do squash. So I may make a mistake or two. By the way, the width wise i left it like this in my editor where the vertical rule is the 80, I think.

image

The second line the hyperlink exceeds the 80, which I think is fine because the text itself won't exceed. If I am wrong about this, let me know. I will happily redo, resquash and resubmit the PR.

Please forgive any mistakes as I seldom contribute to open source and I'm learning.

Thanks 🙏

**Comment by igordejanovic** [comment]
No problem. :) Take your time for learning stuff and thanks for your contributions.

This squash looks perfect. Merging.

**Comment by igordejanovic** [comment]
I just did a reformatting of the note to be consistent with the rest of the docs.
You can see the change [here](https://github.com/igordejanovic/textX/commit/63523981ebcbfac242cbaa50b839c4809e84bc8d).

**Comment by simkimsia** [comment]
Noted, @igordejanovic Will bear this in mind for future docs.

**Pull request merged**
