### PR TITLE
further docu fixes

### PR DESCRIPTION
**Pull request by goto40**
See #97

### CODE REVIEW

**Review by approxit — CHANGES_REQUESTED** [review]
Now docs are clear :)

BUT!

Digging more and actually searching the project with "float" phrase, I found cases that have similar int-float-order problem, and more outdated graphs:

- [Model definition of `InteractCommand`](https://github.com/igordejanovic/textX/blob/dd86244cb9b95bd0238e3ca8790d02da7d82cf54/tests/functional/regressions/test_issue14_obj_proc.py), `4.3` input results in `4` and `0.3` values. I know that is a testcase (even this order typo is not the testcase goal), but testcases are used as examples. Would be nice to mitigate that type of problems in examples.
- Same problem have [Rhapsody example metamodel](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/IBM_Rhapsody/rhapsody.tx), float value is again a two values.
- Outdated [Rhapsody example metamodel graph](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/IBM_Rhapsody/rhapsody.tx.dot.pdf)
- Outdated [Entity example metamodel graph](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/Entity/dotexport/entity_meta.dot.png)
- Outdated [StateMachine example metamodel graph](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/StateMachine/state_machine.tx.dot.png)
- Outdated [pyFiles example metamodel graph](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/pyFlies/pyflies_meta.dot.png)
- Outdated [Workflow example metamodel graph](https://github.com/igordejanovic/textX/blob/dc9ad4b464d41157e8a915511bfbe00d9ca2296d/examples/workflow/workflow_meta.dot.png)

**Comment by igordejanovic** [comment]
@approxit Thanks a lot for catching all those inconsistencies. We really appreciate it.

**Comment by goto40** [comment]
Fixed test_issue_14: amazing that you found this error!

**Comment by goto40** [comment]
@igordejanovic , maybe you could have a look at the last commit (new exports).

I think I catched all issues reported by @approxit ... Good work @approxit !

**Comment by igordejanovic** [comment]
@goto40 Looks good. Merging.
Good work guys!

**Pull request merged**
